name: Build LaTeX document and release PDF
# Everytime a new release is created, build the .pdf for the release and upload it to the release on Github. 
on:
  release:
    types: [created]
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: "manuscript_${GITHUB_REF/refs\/tags\//}.pdf"
          asset_content_type: pdf
  
      - name: Debug
        run: echo ${GITHUB_REF/refs\/tags\//}
